package(default_visibility = ["//visibility:public"])

cc_library(
    name = "keyboard",
    hdrs = ["keyboard.h"],
    srcs = ["keyboard.c"],
    deps = [
        "//src/engine:util",
        "//src/engine:types",
        "//src/engine/render:window",
        "//third_party/glfw:glfw3",
    ]
)
