package(default_visibility = ["//visibility:public"])

cc_library(
    name = "window",
    srcs = ["window.c"],
    hdrs = ["window.h"],
    deps = [
        "//third_party/glfw:glfw3",
        "//third_party/glad:glad",
        "//src/engine:util",
        "//src/engine:types"
    ],
)